### ISSUE TITLE
TO-DO

### ISSUE THREAD

**Issue by asuchardaa** [asuchardaa/WeatherApp#1]
- [x] Aktuální předpověď počasí: Zobrazení aktuální teploty a povětrnostních podmínek. 🌡️
- [x] Předpověď počasí na den dozadu a 5 dní dopředu: Umožňuje uživatelům plánovat na základě budoucího počasí. 📅
- [x] Aktuální stav počasí z domácí meteostanice: Zobrazení aktuálních dat o počasí z domácí meteostanice. 🏡
- [x] Vyhledávání měst: Rychlé a snadné vyhledání dostupných měst z OpenWeatherMap API. 🔍
- [x] JSON Parsing: Efektivní zpracování dat z API pro přesné zobrazení informací. 📊
- [x] Ukládání do databáze: Historie a budoucí předpovědi jsou uloženy pro snadný přístup. 💾
- [x] Oblíbená města: Uživatelé mohou ukládat a načítat oblíbená města pro rychlý přístup. ⭐
- [x] Úprava home fragmentu - zatmavení pozadí a průhledné aktuální počasí
- [x] Úprava hvězdičky dle oblíbeného města -> ANO/NE
- [x] #3
- [x] #4
- [x] Notifikace: Uživatelé mohou dostávat notifikace o změnách počasí. 📩
- [x] Podpora geolokace: Uživatelé mohou získat aktuální předpověď počasí pro svou polohu. 📍
- [ ] #2

**Comment by asuchardaa** [comment]
- [ ] preklad funguje a aplikace si již pamatuje poslední zvolený jazyk i po jejím restartu (byl problém s emulátorem, protože to bralo systémově nastavený jazyk a bylo potřeba tohle v android prostředí ošetřit)
